import type { GrammarId } from './treesitter.js'

export const EXT_TO_GRAMMAR: Record<string, GrammarId> = {
  ts: 'typescript',
  tsx: 'tsx',
  mts: 'typescript',
  cts: 'typescript',
  js: 'javascript',
  jsx: 'javascript',
  mjs: 'javascript',
  cjs: 'javascript',
  py: 'python',
  pyi: 'python',
  go: 'go',
  rs: 'rust',
  java: 'java',
  c: 'c',
  h: 'c',
  cpp: 'cpp',
  cc: 'cpp',
  cxx: 'cpp',
  hpp: 'cpp',
  hh: 'cpp',
  cs: 'c_sharp',
  kt: 'kotlin',
  kts: 'kotlin',
  rb: 'ruby',
  php: 'php',
  swift: 'swift',
  scala: 'scala',
  dart: 'dart',
  zig: 'zig',
  lua: 'lua',
  r: 'r',
  R: 'r',
  ex: 'elixir',
  exs: 'elixir',
  elm: 'elm',
  ml: 'ocaml',
  mli: 'ocaml',
  res: 'rescript',
  sol: 'solidity',
  tla: 'tlaplus',
  m: 'objc',
  mm: 'objc',
  sh: 'bash',
  bash: 'bash',
  vue: 'vue',
  html: 'html',
  htm: 'html',
  css: 'css',
  json: 'json',
  yaml: 'yaml',
  yml: 'yaml',
  toml: 'toml',
  erb: 'embedded_template',
  ejs: 'embedded_template',
  rdl: 'systemrdl',
  ql: 'ql',
  el: 'elisp',
}

export function grammarIdFromPath(relPath: string): GrammarId | null {
  const dot = relPath.lastIndexOf('.')
  if (dot === -1) return null
  const ext = relPath.slice(dot + 1).toLowerCase()
  return EXT_TO_GRAMMAR[ext] ?? null
}

// Pruned during the filesystem walk for EVERY repo, regardless of language.
// Keep this list to dirs that are (a) essentially never hand-written source and
// (b) potentially enormous — so big repos stay fast. Source-colliding names
// like `packages/`, `bin/`, `out/`, `dist/`, `build/`, `target/`, `vendor/`
// deliberately live in the per-grammar lists below instead, so they're only
// excluded when the matching language is actually present.
export const UNIVERSAL_EXCLUDES = [
  // Version control + editor metadata.
  '.git/',
  '.hg/',
  '.svn/',
  '.idea/',
  '.vscode/',
  // JS/TS dependencies — the single biggest tree in most repos.
  'node_modules/',
  // Python virtualenvs + tool caches (dotted ones are unambiguous).
  '.venv/',
  'venv/',
  '__pycache__/',
  '.mypy_cache/',
  '.pytest_cache/',
  '.ruff_cache/',
  '.tox/',
  '.nox/',
  // Framework / bundler / package-manager caches — never source, often huge.
  '.next/',
  '.nuxt/',
  '.svelte-kit/',
  '.astro/',
  '.turbo/',
  '.parcel-cache/',
  '.cache/',
  '.gradle/',
  '.dart_tool/',
  '.cargo/',
  '.vercel/',
  '.netlify/',
  '.output/',
  '.docusaurus/',
]

export const GRAMMAR_EXCLUDES: Record<GrammarId, string[]> = {
  typescript: [
    'node_modules/',
    '.next/',
    '.nuxt/',
    '.svelte-kit/',
    '.astro/',
    '.turbo/',
    '.parcel-cache/',
    '.contentlayer/',
    '.wrangler/',
    '.expo/',
    '.vercel/',
    '.netlify/',
    '.output/',
    '.docusaurus/',
    '.linaria-cache/',
    '.rollup.cache/',
    'storybook-static/',
    'dist/',
    'build/',
    'out/',
    'coverage/',
    '.cache/',
    '*.min.js',
    '*.map',
    '*.bundle.js',
  ],
  tsx: [
    'node_modules/',
    '.next/',
    '.nuxt/',
    '.svelte-kit/',
    '.astro/',
    '.turbo/',
    '.parcel-cache/',
    '.contentlayer/',
    '.wrangler/',
    '.expo/',
    '.vercel/',
    '.netlify/',
    '.output/',
    '.docusaurus/',
    '.linaria-cache/',
    '.rollup.cache/',
    'storybook-static/',
    'dist/',
    'build/',
    'out/',
    'coverage/',
    '.cache/',
    '*.min.js',
    '*.map',
    '*.bundle.js',
  ],
  javascript: [
    'node_modules/',
    '.next/',
    '.nuxt/',
    '.svelte-kit/',
    '.astro/',
    '.turbo/',
    '.parcel-cache/',
    '.contentlayer/',
    '.wrangler/',
    '.expo/',
    '.vercel/',
    '.netlify/',
    '.output/',
    '.docusaurus/',
    '.linaria-cache/',
    '.rollup.cache/',
    'storybook-static/',
    'dist/',
    'build/',
    'out/',
    'coverage/',
    '.cache/',
    '*.min.js',
    '*.map',
    '*.bundle.js',
  ],
  python: [
    '__pycache__/',
    '.venv/',
    'venv/',
    '.env/',
    'env/',
    '.mypy_cache/',
    '.pytest_cache/',
    '.ruff_cache/',
    '.hypothesis/',
    '.tox/',
    '.nox/',
    '.mypy/',
    '.pyre/',
    '.pytype/',
    'dist/',
    'build/',
    '*.egg-info/',
    '*.egg/',
    '*.pyc',
    '*.pyo',
    'htmlcov/',
    '.coverage*',
  ],
  go: [
    'vendor/',
    'bin/',
    'dist/',
    'build/',
  ],
  rust: [
    'target/',
    'dist/',
    'build/',
    '.cargo/',
  ],
  java: [
    '.gradle/',
    'target/',
    'build/',
    'out/',
    '*.class',
    '*.jar',
    '*.war',
  ],
  c: [
    'build/',
    'out/',
    'CMakeFiles/',
    '.cmake/',
    '.clangd/',
    '.ccls-cache/',
    '*.o',
    '*.obj',
    '*.a',
    '*.so',
    '*.dylib',
    '*.dll',
  ],
  cpp: [
    'build/',
    'out/',
    'CMakeFiles/',
    '.cmake/',
    '.clangd/',
    '.ccls-cache/',
    '*.o',
    '*.obj',
    '*.a',
    '*.so',
    '*.dylib',
    '*.dll',
  ],
  c_sharp: [
    'bin/',
    'obj/',
    '.vs/',
    'packages/',
    '*.dll',
    '*.exe',
    '*.nupkg',
  ],
  kotlin: [
    '.gradle/',
    'build/',
    'target/',
    'out/',
    '.kotlin/',
    '*.class',
    '*.jar',
  ],
  ruby: [
    'vendor/bundle/',
    '.bundle/',
    'tmp/',
    'log/',
    '*.gem',
  ],
  php: [
    'vendor/',
    'var/',
    'bootstrap/cache/',
    'dist/',
    'build/',
    '*.phar',
  ],
  swift: [
    '.build/',
    'DerivedData/',
    'Pods/',
    'Carthage/',
    'build/',
  ],
  scala: [
    '.gradle/',
    '.ivy/',
    '.coursier/',
    '.sbt/',
    '.metals/',
    '.bloop/',
    '.bsp/',
    'target/',
    'build/',
    'out/',
    '*.class',
    '*.jar',
  ],
  dart: [
    '.dart_tool/',
    '.pub-cache/',
    'build/',
    'dist/',
    'out/',
    '*.g.dart',
    '*.freezed.dart',
  ],
  zig: [
    'zig-cache/',
    '.zig-cache/',
    'zig-out/',
    'build/',
    'dist/',
    '*.o',
  ],
  lua: [
    'lua_modules/',
    '.luarocks/',
    'build/',
    'dist/',
    '*.luac',
  ],
  r: [
    'renv/',
    'packrat/',
    '.Rproj.user/',
    'build/',
    'dist/',
    '*.o',
    '*.so',
    '*.dll',
  ],
  elixir: [
    'deps/',
    '_build/',
    '.elixir_ls/',
    '.lexical/',
    'rel/',
    'cover/',
    'doc/',
    '*.beam',
  ],
  elm: [
    'elm-stuff/',
    'dist/',
    'build/',
    'out/',
    // NB: never '*.js' here — grammar excludes apply repo-wide, so that would drop
    // every JavaScript source file in every project. Elm's compiled output lives
    // in elm-stuff/ and the build dirs above.
  ],
  ocaml: [
    '_opam/',
    '_build/',
    '.merlin',
    'build/',
    'dist/',
    '*.cmo',
    '*.cmi',
    '*.cmx',
    '*.o',
  ],
  rescript: [
    'node_modules/',
    // ReScript's build output is lib/bs (and lib/es6); excluding a bare 'lib/'
    // would drop every project's lib/ source directory, so scope it.
    'lib/bs/',
    'lib/es6/',
    'lib/ocaml/',
    'dist/',
    'build/',
    'out/',
    '*.bs.js',
  ],
  solidity: [
    'node_modules/',
    'out/',
    'artifacts/',
    'cache/',
    'broadcast/',
    'typechain-types/',
    'build/',
    'dist/',
    '*.abi.json',
  ],
  tlaplus: [
    'build/',
    'dist/',
    'out/',
    '.toolbox/',
    '*.states',
    '*.traces',
  ],
  objc: [
    'build/',
    'DerivedData/',
    'Pods/',
    'build/',
    '*.o',
    '*.obj',
    '*.a',
  ],
  bash: [
    'build/',
    'dist/',
    'out/',
  ],
  vue: [
    'node_modules/',
    '.nuxt/',
    '.output/',
    'dist/',
    'build/',
    'out/',
    'coverage/',
    'storybook-static/',
    '.cache/',
    '.turbo/',
    '.vercel/',
    '.netlify/',
    '*.min.js',
    '*.map',
  ],
  html: [
    'node_modules/',
    'dist/',
    'build/',
    'out/',
    '_site/',
  ],
  css: [
    'node_modules/',
    '.sass-cache/',
    'dist/',
    'build/',
    'out/',
    '*.min.css',
    '*.css.map',
  ],
  json: [
    'node_modules/',
    'dist/',
    'build/',
    'out/',
    'package-lock.json',
    'yarn.lock',
    'pnpm-lock.yaml',
    'bun.lockb',
  ],
  yaml: [
    'dist/',
    'build/',
    'out/',
  ],
  toml: [
    'dist/',
    'build/',
    'out/',
  ],
  embedded_template: [
    'node_modules/',
    'vendor/',
    'dist/',
    'build/',
    'out/',
    'tmp/',
    'log/',
  ],
  systemrdl: [
    'build/',
    'out/',
    'gen/',
    'generated/',
  ],
  ql: [
    'build/',
    'out/',
    'dist/',
    '.codeql/',
    '*.bqrs',
    '*.sarif',
  ],
  elisp: [
    'elpa/',
    'quelpa/',
    'straight/',
    'build/',
    'dist/',
    'out/',
    '*.elc',
    '*.eln',
  ],
}
